<?php

use Application\Entity\Db\These;
use Application\Notification\ValidationPageDeCouvertureNotificationDoctorant;
use Application\View\Renderer\PhpRenderer;

use UnicaenApp\Util;

/**
 * @var PhpRenderer $this
 * @var These       $these
 * @var bool        $isValidation
 *
 * @see ValidationPageDeCouvertureNotificationDoctorant
 */

$appli = $this->appInfos()->nom;
?>

<p>
    <?php echo $these->getDoctorant() ?>,
</p>
<p>
    <em>Ceci est un mail envoyé automatiquement par l'application <?php echo $appli ?>.</em>
</p>

<?php if ($isValidation): ?>
<p>
    Votre jury de soutenance de thèse a été validé. 
</p>
<p>
    Vous devez désormais :
    <ul>
        <li>envoyer votre manuscrit aux membres désignés ;</li>
        <li>
            vous connecter à <a href="<?php echo $this->url('home', [], ['force_canonical' => true]) ?>">l'application <?php echo $appli ?></a> pour effectuer IMPERATIVEMENT le dépôt de votre thèse et de l’autorisation de diffusion avant le
            <?php
            $dateSoutenance = $these->getDateSoutenance() ? $these->getDateSoutenance() : $these->getDatePrevisionSoutenance();
            echo Util::formattedDate( $dateSoutenance->sub( new DateInterval('P1M') ) );
            ?>
            <br>
            Attention : Une fois ce dépôt validé, vous ne pourrez plus modifier votre manuscrit, sauf si  des corrections sont explicitement demandées dans le procès-verbal de soutenance par les membres de votre jury (art 24 – arrêté du 25 mai 2016)
            <br>
            <strong><u>Si vous n’effectuez pas ces démarches dans les délais impartis, votre soutenance de thèse sera annulée.</u></strong>
        </li>
    </ul>
</p>
<p>
    La page de couverture (page recto) étant produite automatiquement par l'application <?php echo $appli ?>, vous
    n'aurez pas à concevoir et inclure cette page de couverture dans le fichier de thèse que vous déposerez dans l'application.
</p>
<?php else: ?>
<p>
    Vous êtes informé·e que l'application <?php echo $appli ?> n'est plus en mesure de produire la page
    de couverture de votre thèse automatiquement à partir des informations de scolarité.
</p>
<p>
    Par conséquent, le processus de dépôt de votre thèse dans l'application est temporairement bloqué. <br>
    Vous recevrez un mail lorsque <?php echo $appli ?> sera de nouveau en mesure de produire la page de couverture
    de manière satisfaisante.
</p>
<?php endif ?>

<p>
    Votre directeur de thèse a été notifié de cette validation.
</p>
<p>
    <a href="<?php echo $this->url('home', [], ['force_canonical' => true]) ?>"
    >Accéder à l'application <?php echo $appli ?></a>.
</p>
